[package]
name = "fiber-autopilot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
ckb-jsonrpc-types = "0.119.0"
ckb-types = "0.119.0"
fiber-ckb-types = { package="ckb-types", version="0.118.0"}
clap = { version = "4.5.29", features = ["derive"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
toml = "0.8.20"
# public RPC
fnn = { git = "https://github.com/jjyr/fiber.git", rev = "745736da68b38999deae75d40c1fdd291d3b0b61" }
ractor = "=0.14.2"
jsonrpsee = { version = "0.24.8", features = [
  "async-client",
  "client-core",
  "http-client",
] }
rand = "0.9.0"
serde_with = { version = "3.12.0", features = ["base64", "macros"] }
# async client
ckb-sdk = { git = "https://github.com/nervosnetwork/ckb-sdk-rust.git", rev = "8adc810d42e2e6b8e7f19feabc16af2aa48a8cb3" }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
secp256k1 = "0.28.2"
